// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: arm_command.proto
// Protobuf C++ Version: 5.28.2

#include "arm_command.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ArmCommand::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : right_joint_{},
        left_joint_{},
        request_state_{0u},
        velocity_gain_{0},
        acceleration_gain_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ArmCommand::ArmCommand(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ArmCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArmCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArmCommandDefaultTypeInternal() {}
  union {
    ArmCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArmCommandDefaultTypeInternal _ArmCommand_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_arm_5fcommand_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_arm_5fcommand_2eproto = nullptr;
const ::uint32_t
    TableStruct_arm_5fcommand_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _impl_.request_state_),
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _impl_.right_joint_),
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _impl_.left_joint_),
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _impl_.velocity_gain_),
        PROTOBUF_FIELD_OFFSET(::ArmCommand, _impl_.acceleration_gain_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ArmCommand)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ArmCommand_default_instance_._instance,
};
const char descriptor_table_protodef_arm_5fcommand_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021arm_command.proto\032\023joint_command.proto"
    "\"\234\001\n\nArmCommand\022\025\n\rrequest_state\030\001 \001(\r\022\""
    "\n\013right_joint\030\002 \003(\0132\r.JointCommand\022!\n\nle"
    "ft_joint\030\003 \003(\0132\r.JointCommand\022\025\n\rvelocit"
    "y_gain\030\004 \001(\002\022\031\n\021acceleration_gain\030\005 \001(\002b"
    "\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_arm_5fcommand_2eproto_deps[1] =
    {
        &::descriptor_table_joint_5fcommand_2eproto,
};
static ::absl::once_flag descriptor_table_arm_5fcommand_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_arm_5fcommand_2eproto = {
    false,
    false,
    207,
    descriptor_table_protodef_arm_5fcommand_2eproto,
    "arm_command.proto",
    &descriptor_table_arm_5fcommand_2eproto_once,
    descriptor_table_arm_5fcommand_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_arm_5fcommand_2eproto::offsets,
    file_level_enum_descriptors_arm_5fcommand_2eproto,
    file_level_service_descriptors_arm_5fcommand_2eproto,
};
// ===================================================================

class ArmCommand::_Internal {
 public:
};

void ArmCommand::clear_right_joint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_joint_.Clear();
}
void ArmCommand::clear_left_joint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_joint_.Clear();
}
ArmCommand::ArmCommand(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ArmCommand)
}
inline PROTOBUF_NDEBUG_INLINE ArmCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ArmCommand& from_msg)
      : right_joint_{visibility, arena, from.right_joint_},
        left_joint_{visibility, arena, from.left_joint_},
        _cached_size_{0} {}

ArmCommand::ArmCommand(
    ::google::protobuf::Arena* arena,
    const ArmCommand& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ArmCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_state_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, request_state_),
           offsetof(Impl_, acceleration_gain_) -
               offsetof(Impl_, request_state_) +
               sizeof(Impl_::acceleration_gain_));

  // @@protoc_insertion_point(copy_constructor:ArmCommand)
}
inline PROTOBUF_NDEBUG_INLINE ArmCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : right_joint_{visibility, arena},
        left_joint_{visibility, arena},
        _cached_size_{0} {}

inline void ArmCommand::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_state_),
           0,
           offsetof(Impl_, acceleration_gain_) -
               offsetof(Impl_, request_state_) +
               sizeof(Impl_::acceleration_gain_));
}
ArmCommand::~ArmCommand() {
  // @@protoc_insertion_point(destructor:ArmCommand)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ArmCommand::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ArmCommand::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ArmCommand_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ArmCommand::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ArmCommand>(),
            ::google::protobuf::Message::GetNewImpl<ArmCommand>(),
            ::google::protobuf::Message::GetClearImpl<ArmCommand>(), &ArmCommand::ByteSizeLong,
                &ArmCommand::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_._cached_size_),
            false,
        },
        &ArmCommand::kDescriptorMethods,
        &descriptor_table_arm_5fcommand_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ArmCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2> ArmCommand::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ArmCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 request_state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArmCommand, _impl_.request_state_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.request_state_)}},
    // repeated .JointCommand right_joint = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.right_joint_)}},
    // repeated .JointCommand left_joint = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 1, PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.left_joint_)}},
    // float velocity_gain = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.velocity_gain_)}},
    // float acceleration_gain = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.acceleration_gain_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 request_state = 1;
    {PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.request_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated .JointCommand right_joint = 2;
    {PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.right_joint_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .JointCommand left_joint = 3;
    {PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.left_joint_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // float velocity_gain = 4;
    {PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.velocity_gain_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float acceleration_gain = 5;
    {PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.acceleration_gain_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }}, {{
    {::_pbi::TcParser::GetTable<::JointCommand>()},
    {::_pbi::TcParser::GetTable<::JointCommand>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ArmCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:ArmCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.right_joint_.Clear();
  _impl_.left_joint_.Clear();
  ::memset(&_impl_.request_state_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.acceleration_gain_) -
      reinterpret_cast<char*>(&_impl_.request_state_)) + sizeof(_impl_.acceleration_gain_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ArmCommand::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ArmCommand& this_ = static_cast<const ArmCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ArmCommand::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ArmCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ArmCommand)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 request_state = 1;
          if (this_._internal_request_state() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_request_state(), target);
          }

          // repeated .JointCommand right_joint = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_right_joint_size());
               i < n; i++) {
            const auto& repfield = this_._internal_right_joint().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .JointCommand left_joint = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_left_joint_size());
               i < n; i++) {
            const auto& repfield = this_._internal_left_joint().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // float velocity_gain = 4;
          if (::absl::bit_cast<::uint32_t>(this_._internal_velocity_gain()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                4, this_._internal_velocity_gain(), target);
          }

          // float acceleration_gain = 5;
          if (::absl::bit_cast<::uint32_t>(this_._internal_acceleration_gain()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                5, this_._internal_acceleration_gain(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ArmCommand)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ArmCommand::ByteSizeLong(const MessageLite& base) {
          const ArmCommand& this_ = static_cast<const ArmCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ArmCommand::ByteSizeLong() const {
          const ArmCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ArmCommand)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .JointCommand right_joint = 2;
             {
              total_size += 1UL * this_._internal_right_joint_size();
              for (const auto& msg : this_._internal_right_joint()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .JointCommand left_joint = 3;
             {
              total_size += 1UL * this_._internal_left_joint_size();
              for (const auto& msg : this_._internal_left_joint()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // uint32 request_state = 1;
            if (this_._internal_request_state() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_request_state());
            }
            // float velocity_gain = 4;
            if (::absl::bit_cast<::uint32_t>(this_._internal_velocity_gain()) != 0) {
              total_size += 5;
            }
            // float acceleration_gain = 5;
            if (::absl::bit_cast<::uint32_t>(this_._internal_acceleration_gain()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ArmCommand::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ArmCommand*>(&to_msg);
  auto& from = static_cast<const ArmCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ArmCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_right_joint()->MergeFrom(
      from._internal_right_joint());
  _this->_internal_mutable_left_joint()->MergeFrom(
      from._internal_left_joint());
  if (from._internal_request_state() != 0) {
    _this->_impl_.request_state_ = from._impl_.request_state_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_velocity_gain()) != 0) {
    _this->_impl_.velocity_gain_ = from._impl_.velocity_gain_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_acceleration_gain()) != 0) {
    _this->_impl_.acceleration_gain_ = from._impl_.acceleration_gain_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ArmCommand::CopyFrom(const ArmCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArmCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ArmCommand::InternalSwap(ArmCommand* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.right_joint_.InternalSwap(&other->_impl_.right_joint_);
  _impl_.left_joint_.InternalSwap(&other->_impl_.left_joint_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.acceleration_gain_)
      + sizeof(ArmCommand::_impl_.acceleration_gain_)
      - PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.request_state_)>(
          reinterpret_cast<char*>(&_impl_.request_state_),
          reinterpret_cast<char*>(&other->_impl_.request_state_));
}

::google::protobuf::Metadata ArmCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_arm_5fcommand_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
