// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: arm_command.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_arm_5fcommand_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_arm_5fcommand_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "joint_command.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_arm_5fcommand_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_arm_5fcommand_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_arm_5fcommand_2eproto;
class ArmCommand;
struct ArmCommandDefaultTypeInternal;
extern ArmCommandDefaultTypeInternal _ArmCommand_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ArmCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ArmCommand) */ {
 public:
  inline ArmCommand() : ArmCommand(nullptr) {}
  ~ArmCommand() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ArmCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline ArmCommand(const ArmCommand& from) : ArmCommand(nullptr, from) {}
  inline ArmCommand(ArmCommand&& from) noexcept
      : ArmCommand(nullptr, std::move(from)) {}
  inline ArmCommand& operator=(const ArmCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArmCommand& operator=(ArmCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArmCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArmCommand* internal_default_instance() {
    return reinterpret_cast<const ArmCommand*>(
        &_ArmCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ArmCommand& a, ArmCommand& b) { a.Swap(&b); }
  inline void Swap(ArmCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArmCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArmCommand* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ArmCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ArmCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ArmCommand& from) { ArmCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ArmCommand* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ArmCommand"; }

 protected:
  explicit ArmCommand(::google::protobuf::Arena* arena);
  ArmCommand(::google::protobuf::Arena* arena, const ArmCommand& from);
  ArmCommand(::google::protobuf::Arena* arena, ArmCommand&& from) noexcept
      : ArmCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRightJointFieldNumber = 2,
    kLeftJointFieldNumber = 3,
    kRequestStateFieldNumber = 1,
    kVelocityGainFieldNumber = 4,
    kAccelerationGainFieldNumber = 5,
  };
  // repeated .JointCommand right_joint = 2;
  int right_joint_size() const;
  private:
  int _internal_right_joint_size() const;

  public:
  void clear_right_joint() ;
  ::JointCommand* mutable_right_joint(int index);
  ::google::protobuf::RepeatedPtrField<::JointCommand>* mutable_right_joint();

  private:
  const ::google::protobuf::RepeatedPtrField<::JointCommand>& _internal_right_joint() const;
  ::google::protobuf::RepeatedPtrField<::JointCommand>* _internal_mutable_right_joint();
  public:
  const ::JointCommand& right_joint(int index) const;
  ::JointCommand* add_right_joint();
  const ::google::protobuf::RepeatedPtrField<::JointCommand>& right_joint() const;
  // repeated .JointCommand left_joint = 3;
  int left_joint_size() const;
  private:
  int _internal_left_joint_size() const;

  public:
  void clear_left_joint() ;
  ::JointCommand* mutable_left_joint(int index);
  ::google::protobuf::RepeatedPtrField<::JointCommand>* mutable_left_joint();

  private:
  const ::google::protobuf::RepeatedPtrField<::JointCommand>& _internal_left_joint() const;
  ::google::protobuf::RepeatedPtrField<::JointCommand>* _internal_mutable_left_joint();
  public:
  const ::JointCommand& left_joint(int index) const;
  ::JointCommand* add_left_joint();
  const ::google::protobuf::RepeatedPtrField<::JointCommand>& left_joint() const;
  // uint32 request_state = 1;
  void clear_request_state() ;
  ::uint32_t request_state() const;
  void set_request_state(::uint32_t value);

  private:
  ::uint32_t _internal_request_state() const;
  void _internal_set_request_state(::uint32_t value);

  public:
  // float velocity_gain = 4;
  void clear_velocity_gain() ;
  float velocity_gain() const;
  void set_velocity_gain(float value);

  private:
  float _internal_velocity_gain() const;
  void _internal_set_velocity_gain(float value);

  public:
  // float acceleration_gain = 5;
  void clear_acceleration_gain() ;
  float acceleration_gain() const;
  void set_acceleration_gain(float value);

  private:
  float _internal_acceleration_gain() const;
  void _internal_set_acceleration_gain(float value);

  public:
  // @@protoc_insertion_point(class_scope:ArmCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ArmCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ArmCommand& from_msg);
    ::google::protobuf::RepeatedPtrField< ::JointCommand > right_joint_;
    ::google::protobuf::RepeatedPtrField< ::JointCommand > left_joint_;
    ::uint32_t request_state_;
    float velocity_gain_;
    float acceleration_gain_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_arm_5fcommand_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ArmCommand

// uint32 request_state = 1;
inline void ArmCommand::clear_request_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_state_ = 0u;
}
inline ::uint32_t ArmCommand::request_state() const {
  // @@protoc_insertion_point(field_get:ArmCommand.request_state)
  return _internal_request_state();
}
inline void ArmCommand::set_request_state(::uint32_t value) {
  _internal_set_request_state(value);
  // @@protoc_insertion_point(field_set:ArmCommand.request_state)
}
inline ::uint32_t ArmCommand::_internal_request_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_state_;
}
inline void ArmCommand::_internal_set_request_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_state_ = value;
}

// repeated .JointCommand right_joint = 2;
inline int ArmCommand::_internal_right_joint_size() const {
  return _internal_right_joint().size();
}
inline int ArmCommand::right_joint_size() const {
  return _internal_right_joint_size();
}
inline ::JointCommand* ArmCommand::mutable_right_joint(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ArmCommand.right_joint)
  return _internal_mutable_right_joint()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::JointCommand>* ArmCommand::mutable_right_joint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmCommand.right_joint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_right_joint();
}
inline const ::JointCommand& ArmCommand::right_joint(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ArmCommand.right_joint)
  return _internal_right_joint().Get(index);
}
inline ::JointCommand* ArmCommand::add_right_joint() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::JointCommand* _add = _internal_mutable_right_joint()->Add();
  // @@protoc_insertion_point(field_add:ArmCommand.right_joint)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::JointCommand>& ArmCommand::right_joint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmCommand.right_joint)
  return _internal_right_joint();
}
inline const ::google::protobuf::RepeatedPtrField<::JointCommand>&
ArmCommand::_internal_right_joint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_joint_;
}
inline ::google::protobuf::RepeatedPtrField<::JointCommand>*
ArmCommand::_internal_mutable_right_joint() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.right_joint_;
}

// repeated .JointCommand left_joint = 3;
inline int ArmCommand::_internal_left_joint_size() const {
  return _internal_left_joint().size();
}
inline int ArmCommand::left_joint_size() const {
  return _internal_left_joint_size();
}
inline ::JointCommand* ArmCommand::mutable_left_joint(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ArmCommand.left_joint)
  return _internal_mutable_left_joint()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::JointCommand>* ArmCommand::mutable_left_joint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmCommand.left_joint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_left_joint();
}
inline const ::JointCommand& ArmCommand::left_joint(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ArmCommand.left_joint)
  return _internal_left_joint().Get(index);
}
inline ::JointCommand* ArmCommand::add_left_joint() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::JointCommand* _add = _internal_mutable_left_joint()->Add();
  // @@protoc_insertion_point(field_add:ArmCommand.left_joint)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::JointCommand>& ArmCommand::left_joint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmCommand.left_joint)
  return _internal_left_joint();
}
inline const ::google::protobuf::RepeatedPtrField<::JointCommand>&
ArmCommand::_internal_left_joint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_joint_;
}
inline ::google::protobuf::RepeatedPtrField<::JointCommand>*
ArmCommand::_internal_mutable_left_joint() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.left_joint_;
}

// float velocity_gain = 4;
inline void ArmCommand::clear_velocity_gain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_gain_ = 0;
}
inline float ArmCommand::velocity_gain() const {
  // @@protoc_insertion_point(field_get:ArmCommand.velocity_gain)
  return _internal_velocity_gain();
}
inline void ArmCommand::set_velocity_gain(float value) {
  _internal_set_velocity_gain(value);
  // @@protoc_insertion_point(field_set:ArmCommand.velocity_gain)
}
inline float ArmCommand::_internal_velocity_gain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_gain_;
}
inline void ArmCommand::_internal_set_velocity_gain(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_gain_ = value;
}

// float acceleration_gain = 5;
inline void ArmCommand::clear_acceleration_gain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acceleration_gain_ = 0;
}
inline float ArmCommand::acceleration_gain() const {
  // @@protoc_insertion_point(field_get:ArmCommand.acceleration_gain)
  return _internal_acceleration_gain();
}
inline void ArmCommand::set_acceleration_gain(float value) {
  _internal_set_acceleration_gain(value);
  // @@protoc_insertion_point(field_set:ArmCommand.acceleration_gain)
}
inline float ArmCommand::_internal_acceleration_gain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.acceleration_gain_;
}
inline void ArmCommand::_internal_set_acceleration_gain(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acceleration_gain_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_arm_5fcommand_2eproto_2epb_2eh
