// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: arm_state.proto
// Protobuf C++ Version: 5.28.2

#include "arm_state.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ArmState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : right_joint_{},
        left_joint_{},
        right_tool_force_{},
        left_tool_force_{},
        state_{0u},
        fault_code_{0u},
        is_reach_target_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ArmState::ArmState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ArmStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArmStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArmStateDefaultTypeInternal() {}
  union {
    ArmState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArmStateDefaultTypeInternal _ArmState_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_arm_5fstate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_arm_5fstate_2eproto = nullptr;
const ::uint32_t
    TableStruct_arm_5fstate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ArmState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.fault_code_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.is_reach_target_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.right_joint_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.left_joint_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.right_tool_force_),
        PROTOBUF_FIELD_OFFSET(::ArmState, _impl_.left_tool_force_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ArmState)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ArmState_default_instance_._instance,
};
const char descriptor_table_protodef_arm_5fstate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017arm_state.proto\032\021joint_state.proto\"\274\001\n"
    "\010ArmState\022\r\n\005state\030\001 \001(\r\022\022\n\nfault_code\030\002"
    " \001(\r\022\027\n\017is_reach_target\030\003 \001(\010\022 \n\013right_j"
    "oint\030\004 \003(\0132\013.JointState\022\037\n\nleft_joint\030\005 "
    "\003(\0132\013.JointState\022\030\n\020right_tool_force\030\006 \003"
    "(\002\022\027\n\017left_tool_force\030\007 \003(\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_arm_5fstate_2eproto_deps[1] =
    {
        &::descriptor_table_joint_5fstate_2eproto,
};
static ::absl::once_flag descriptor_table_arm_5fstate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_arm_5fstate_2eproto = {
    false,
    false,
    235,
    descriptor_table_protodef_arm_5fstate_2eproto,
    "arm_state.proto",
    &descriptor_table_arm_5fstate_2eproto_once,
    descriptor_table_arm_5fstate_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_arm_5fstate_2eproto::offsets,
    file_level_enum_descriptors_arm_5fstate_2eproto,
    file_level_service_descriptors_arm_5fstate_2eproto,
};
// ===================================================================

class ArmState::_Internal {
 public:
};

void ArmState::clear_right_joint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_joint_.Clear();
}
void ArmState::clear_left_joint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_joint_.Clear();
}
ArmState::ArmState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ArmState)
}
inline PROTOBUF_NDEBUG_INLINE ArmState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ArmState& from_msg)
      : right_joint_{visibility, arena, from.right_joint_},
        left_joint_{visibility, arena, from.left_joint_},
        right_tool_force_{visibility, arena, from.right_tool_force_},
        left_tool_force_{visibility, arena, from.left_tool_force_},
        _cached_size_{0} {}

ArmState::ArmState(
    ::google::protobuf::Arena* arena,
    const ArmState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ArmState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, state_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, state_),
           offsetof(Impl_, is_reach_target_) -
               offsetof(Impl_, state_) +
               sizeof(Impl_::is_reach_target_));

  // @@protoc_insertion_point(copy_constructor:ArmState)
}
inline PROTOBUF_NDEBUG_INLINE ArmState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : right_joint_{visibility, arena},
        left_joint_{visibility, arena},
        right_tool_force_{visibility, arena},
        left_tool_force_{visibility, arena},
        _cached_size_{0} {}

inline void ArmState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, state_),
           0,
           offsetof(Impl_, is_reach_target_) -
               offsetof(Impl_, state_) +
               sizeof(Impl_::is_reach_target_));
}
ArmState::~ArmState() {
  // @@protoc_insertion_point(destructor:ArmState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ArmState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ArmState::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ArmState_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ArmState::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ArmState>(),
            ::google::protobuf::Message::GetNewImpl<ArmState>(),
            ::google::protobuf::Message::GetClearImpl<ArmState>(), &ArmState::ByteSizeLong,
                &ArmState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ArmState, _impl_._cached_size_),
            false,
        },
        &ArmState::kDescriptorMethods,
        &descriptor_table_arm_5fstate_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ArmState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 2, 0, 2> ArmState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ArmState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArmState, _impl_.state_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.state_)}},
    // uint32 fault_code = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ArmState, _impl_.fault_code_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.fault_code_)}},
    // bool is_reach_target = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ArmState, _impl_.is_reach_target_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.is_reach_target_)}},
    // repeated .JointState right_joint = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.right_joint_)}},
    // repeated .JointState left_joint = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 1, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.left_joint_)}},
    // repeated float right_tool_force = 6;
    {::_pbi::TcParser::FastF32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.right_tool_force_)}},
    // repeated float left_tool_force = 7;
    {::_pbi::TcParser::FastF32P1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(ArmState, _impl_.left_tool_force_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 state = 1;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 fault_code = 2;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.fault_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool is_reach_target = 3;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.is_reach_target_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated .JointState right_joint = 4;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.right_joint_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .JointState left_joint = 5;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.left_joint_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated float right_tool_force = 6;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.right_tool_force_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float left_tool_force = 7;
    {PROTOBUF_FIELD_OFFSET(ArmState, _impl_.left_tool_force_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }}, {{
    {::_pbi::TcParser::GetTable<::JointState>()},
    {::_pbi::TcParser::GetTable<::JointState>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ArmState::Clear() {
// @@protoc_insertion_point(message_clear_start:ArmState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.right_joint_.Clear();
  _impl_.left_joint_.Clear();
  _impl_.right_tool_force_.Clear();
  _impl_.left_tool_force_.Clear();
  ::memset(&_impl_.state_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_reach_target_) -
      reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.is_reach_target_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ArmState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ArmState& this_ = static_cast<const ArmState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ArmState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ArmState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ArmState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 state = 1;
          if (this_._internal_state() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_state(), target);
          }

          // uint32 fault_code = 2;
          if (this_._internal_fault_code() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_fault_code(), target);
          }

          // bool is_reach_target = 3;
          if (this_._internal_is_reach_target() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_is_reach_target(), target);
          }

          // repeated .JointState right_joint = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_right_joint_size());
               i < n; i++) {
            const auto& repfield = this_._internal_right_joint().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .JointState left_joint = 5;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_left_joint_size());
               i < n; i++) {
            const auto& repfield = this_._internal_left_joint().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    5, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated float right_tool_force = 6;
          if (this_._internal_right_tool_force_size() > 0) {
            target = stream->WriteFixedPacked(6, this_._internal_right_tool_force(), target);
          }

          // repeated float left_tool_force = 7;
          if (this_._internal_left_tool_force_size() > 0) {
            target = stream->WriteFixedPacked(7, this_._internal_left_tool_force(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ArmState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ArmState::ByteSizeLong(const MessageLite& base) {
          const ArmState& this_ = static_cast<const ArmState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ArmState::ByteSizeLong() const {
          const ArmState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ArmState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .JointState right_joint = 4;
             {
              total_size += 1UL * this_._internal_right_joint_size();
              for (const auto& msg : this_._internal_right_joint()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .JointState left_joint = 5;
             {
              total_size += 1UL * this_._internal_left_joint_size();
              for (const auto& msg : this_._internal_left_joint()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated float right_tool_force = 6;
             {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_right_tool_force_size())
              ;
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
            // repeated float left_tool_force = 7;
             {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_left_tool_force_size())
              ;
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
          }
           {
            // uint32 state = 1;
            if (this_._internal_state() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_state());
            }
            // uint32 fault_code = 2;
            if (this_._internal_fault_code() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_fault_code());
            }
            // bool is_reach_target = 3;
            if (this_._internal_is_reach_target() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ArmState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ArmState*>(&to_msg);
  auto& from = static_cast<const ArmState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ArmState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_right_joint()->MergeFrom(
      from._internal_right_joint());
  _this->_internal_mutable_left_joint()->MergeFrom(
      from._internal_left_joint());
  _this->_internal_mutable_right_tool_force()->MergeFrom(from._internal_right_tool_force());
  _this->_internal_mutable_left_tool_force()->MergeFrom(from._internal_left_tool_force());
  if (from._internal_state() != 0) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  if (from._internal_fault_code() != 0) {
    _this->_impl_.fault_code_ = from._impl_.fault_code_;
  }
  if (from._internal_is_reach_target() != 0) {
    _this->_impl_.is_reach_target_ = from._impl_.is_reach_target_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ArmState::CopyFrom(const ArmState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArmState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ArmState::InternalSwap(ArmState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.right_joint_.InternalSwap(&other->_impl_.right_joint_);
  _impl_.left_joint_.InternalSwap(&other->_impl_.left_joint_);
  _impl_.right_tool_force_.InternalSwap(&other->_impl_.right_tool_force_);
  _impl_.left_tool_force_.InternalSwap(&other->_impl_.left_tool_force_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArmState, _impl_.is_reach_target_)
      + sizeof(ArmState::_impl_.is_reach_target_)
      - PROTOBUF_FIELD_OFFSET(ArmState, _impl_.state_)>(
          reinterpret_cast<char*>(&_impl_.state_),
          reinterpret_cast<char*>(&other->_impl_.state_));
}

::google::protobuf::Metadata ArmState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_arm_5fstate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
