// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: arm_state.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_arm_5fstate_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_arm_5fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "joint_state.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_arm_5fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_arm_5fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_arm_5fstate_2eproto;
class ArmState;
struct ArmStateDefaultTypeInternal;
extern ArmStateDefaultTypeInternal _ArmState_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ArmState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ArmState) */ {
 public:
  inline ArmState() : ArmState(nullptr) {}
  ~ArmState() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ArmState(
      ::google::protobuf::internal::ConstantInitialized);

  inline ArmState(const ArmState& from) : ArmState(nullptr, from) {}
  inline ArmState(ArmState&& from) noexcept
      : ArmState(nullptr, std::move(from)) {}
  inline ArmState& operator=(const ArmState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArmState& operator=(ArmState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArmState& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArmState* internal_default_instance() {
    return reinterpret_cast<const ArmState*>(
        &_ArmState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ArmState& a, ArmState& b) { a.Swap(&b); }
  inline void Swap(ArmState* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArmState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArmState* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ArmState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ArmState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ArmState& from) { ArmState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ArmState* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ArmState"; }

 protected:
  explicit ArmState(::google::protobuf::Arena* arena);
  ArmState(::google::protobuf::Arena* arena, const ArmState& from);
  ArmState(::google::protobuf::Arena* arena, ArmState&& from) noexcept
      : ArmState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRightJointFieldNumber = 4,
    kLeftJointFieldNumber = 5,
    kRightToolForceFieldNumber = 6,
    kLeftToolForceFieldNumber = 7,
    kStateFieldNumber = 1,
    kFaultCodeFieldNumber = 2,
    kIsReachTargetFieldNumber = 3,
  };
  // repeated .JointState right_joint = 4;
  int right_joint_size() const;
  private:
  int _internal_right_joint_size() const;

  public:
  void clear_right_joint() ;
  ::JointState* mutable_right_joint(int index);
  ::google::protobuf::RepeatedPtrField<::JointState>* mutable_right_joint();

  private:
  const ::google::protobuf::RepeatedPtrField<::JointState>& _internal_right_joint() const;
  ::google::protobuf::RepeatedPtrField<::JointState>* _internal_mutable_right_joint();
  public:
  const ::JointState& right_joint(int index) const;
  ::JointState* add_right_joint();
  const ::google::protobuf::RepeatedPtrField<::JointState>& right_joint() const;
  // repeated .JointState left_joint = 5;
  int left_joint_size() const;
  private:
  int _internal_left_joint_size() const;

  public:
  void clear_left_joint() ;
  ::JointState* mutable_left_joint(int index);
  ::google::protobuf::RepeatedPtrField<::JointState>* mutable_left_joint();

  private:
  const ::google::protobuf::RepeatedPtrField<::JointState>& _internal_left_joint() const;
  ::google::protobuf::RepeatedPtrField<::JointState>* _internal_mutable_left_joint();
  public:
  const ::JointState& left_joint(int index) const;
  ::JointState* add_left_joint();
  const ::google::protobuf::RepeatedPtrField<::JointState>& left_joint() const;
  // repeated float right_tool_force = 6;
  int right_tool_force_size() const;
  private:
  int _internal_right_tool_force_size() const;

  public:
  void clear_right_tool_force() ;
  float right_tool_force(int index) const;
  void set_right_tool_force(int index, float value);
  void add_right_tool_force(float value);
  const ::google::protobuf::RepeatedField<float>& right_tool_force() const;
  ::google::protobuf::RepeatedField<float>* mutable_right_tool_force();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_right_tool_force() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_right_tool_force();

  public:
  // repeated float left_tool_force = 7;
  int left_tool_force_size() const;
  private:
  int _internal_left_tool_force_size() const;

  public:
  void clear_left_tool_force() ;
  float left_tool_force(int index) const;
  void set_left_tool_force(int index, float value);
  void add_left_tool_force(float value);
  const ::google::protobuf::RepeatedField<float>& left_tool_force() const;
  ::google::protobuf::RepeatedField<float>* mutable_left_tool_force();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_left_tool_force() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_left_tool_force();

  public:
  // uint32 state = 1;
  void clear_state() ;
  ::uint32_t state() const;
  void set_state(::uint32_t value);

  private:
  ::uint32_t _internal_state() const;
  void _internal_set_state(::uint32_t value);

  public:
  // uint32 fault_code = 2;
  void clear_fault_code() ;
  ::uint32_t fault_code() const;
  void set_fault_code(::uint32_t value);

  private:
  ::uint32_t _internal_fault_code() const;
  void _internal_set_fault_code(::uint32_t value);

  public:
  // bool is_reach_target = 3;
  void clear_is_reach_target() ;
  bool is_reach_target() const;
  void set_is_reach_target(bool value);

  private:
  bool _internal_is_reach_target() const;
  void _internal_set_is_reach_target(bool value);

  public:
  // @@protoc_insertion_point(class_scope:ArmState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ArmState_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ArmState& from_msg);
    ::google::protobuf::RepeatedPtrField< ::JointState > right_joint_;
    ::google::protobuf::RepeatedPtrField< ::JointState > left_joint_;
    ::google::protobuf::RepeatedField<float> right_tool_force_;
    ::google::protobuf::RepeatedField<float> left_tool_force_;
    ::uint32_t state_;
    ::uint32_t fault_code_;
    bool is_reach_target_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_arm_5fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ArmState

// uint32 state = 1;
inline void ArmState::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0u;
}
inline ::uint32_t ArmState::state() const {
  // @@protoc_insertion_point(field_get:ArmState.state)
  return _internal_state();
}
inline void ArmState::set_state(::uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:ArmState.state)
}
inline ::uint32_t ArmState::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_;
}
inline void ArmState::_internal_set_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// uint32 fault_code = 2;
inline void ArmState::clear_fault_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = 0u;
}
inline ::uint32_t ArmState::fault_code() const {
  // @@protoc_insertion_point(field_get:ArmState.fault_code)
  return _internal_fault_code();
}
inline void ArmState::set_fault_code(::uint32_t value) {
  _internal_set_fault_code(value);
  // @@protoc_insertion_point(field_set:ArmState.fault_code)
}
inline ::uint32_t ArmState::_internal_fault_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fault_code_;
}
inline void ArmState::_internal_set_fault_code(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = value;
}

// bool is_reach_target = 3;
inline void ArmState::clear_is_reach_target() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_reach_target_ = false;
}
inline bool ArmState::is_reach_target() const {
  // @@protoc_insertion_point(field_get:ArmState.is_reach_target)
  return _internal_is_reach_target();
}
inline void ArmState::set_is_reach_target(bool value) {
  _internal_set_is_reach_target(value);
  // @@protoc_insertion_point(field_set:ArmState.is_reach_target)
}
inline bool ArmState::_internal_is_reach_target() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_reach_target_;
}
inline void ArmState::_internal_set_is_reach_target(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_reach_target_ = value;
}

// repeated .JointState right_joint = 4;
inline int ArmState::_internal_right_joint_size() const {
  return _internal_right_joint().size();
}
inline int ArmState::right_joint_size() const {
  return _internal_right_joint_size();
}
inline ::JointState* ArmState::mutable_right_joint(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ArmState.right_joint)
  return _internal_mutable_right_joint()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::JointState>* ArmState::mutable_right_joint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmState.right_joint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_right_joint();
}
inline const ::JointState& ArmState::right_joint(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ArmState.right_joint)
  return _internal_right_joint().Get(index);
}
inline ::JointState* ArmState::add_right_joint() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::JointState* _add = _internal_mutable_right_joint()->Add();
  // @@protoc_insertion_point(field_add:ArmState.right_joint)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::JointState>& ArmState::right_joint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmState.right_joint)
  return _internal_right_joint();
}
inline const ::google::protobuf::RepeatedPtrField<::JointState>&
ArmState::_internal_right_joint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_joint_;
}
inline ::google::protobuf::RepeatedPtrField<::JointState>*
ArmState::_internal_mutable_right_joint() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.right_joint_;
}

// repeated .JointState left_joint = 5;
inline int ArmState::_internal_left_joint_size() const {
  return _internal_left_joint().size();
}
inline int ArmState::left_joint_size() const {
  return _internal_left_joint_size();
}
inline ::JointState* ArmState::mutable_left_joint(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ArmState.left_joint)
  return _internal_mutable_left_joint()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::JointState>* ArmState::mutable_left_joint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmState.left_joint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_left_joint();
}
inline const ::JointState& ArmState::left_joint(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ArmState.left_joint)
  return _internal_left_joint().Get(index);
}
inline ::JointState* ArmState::add_left_joint() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::JointState* _add = _internal_mutable_left_joint()->Add();
  // @@protoc_insertion_point(field_add:ArmState.left_joint)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::JointState>& ArmState::left_joint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmState.left_joint)
  return _internal_left_joint();
}
inline const ::google::protobuf::RepeatedPtrField<::JointState>&
ArmState::_internal_left_joint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_joint_;
}
inline ::google::protobuf::RepeatedPtrField<::JointState>*
ArmState::_internal_mutable_left_joint() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.left_joint_;
}

// repeated float right_tool_force = 6;
inline int ArmState::_internal_right_tool_force_size() const {
  return _internal_right_tool_force().size();
}
inline int ArmState::right_tool_force_size() const {
  return _internal_right_tool_force_size();
}
inline void ArmState::clear_right_tool_force() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_tool_force_.Clear();
}
inline float ArmState::right_tool_force(int index) const {
  // @@protoc_insertion_point(field_get:ArmState.right_tool_force)
  return _internal_right_tool_force().Get(index);
}
inline void ArmState::set_right_tool_force(int index, float value) {
  _internal_mutable_right_tool_force()->Set(index, value);
  // @@protoc_insertion_point(field_set:ArmState.right_tool_force)
}
inline void ArmState::add_right_tool_force(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_right_tool_force()->Add(value);
  // @@protoc_insertion_point(field_add:ArmState.right_tool_force)
}
inline const ::google::protobuf::RepeatedField<float>& ArmState::right_tool_force() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmState.right_tool_force)
  return _internal_right_tool_force();
}
inline ::google::protobuf::RepeatedField<float>* ArmState::mutable_right_tool_force()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmState.right_tool_force)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_right_tool_force();
}
inline const ::google::protobuf::RepeatedField<float>&
ArmState::_internal_right_tool_force() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_tool_force_;
}
inline ::google::protobuf::RepeatedField<float>* ArmState::_internal_mutable_right_tool_force() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.right_tool_force_;
}

// repeated float left_tool_force = 7;
inline int ArmState::_internal_left_tool_force_size() const {
  return _internal_left_tool_force().size();
}
inline int ArmState::left_tool_force_size() const {
  return _internal_left_tool_force_size();
}
inline void ArmState::clear_left_tool_force() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_tool_force_.Clear();
}
inline float ArmState::left_tool_force(int index) const {
  // @@protoc_insertion_point(field_get:ArmState.left_tool_force)
  return _internal_left_tool_force().Get(index);
}
inline void ArmState::set_left_tool_force(int index, float value) {
  _internal_mutable_left_tool_force()->Set(index, value);
  // @@protoc_insertion_point(field_set:ArmState.left_tool_force)
}
inline void ArmState::add_left_tool_force(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_left_tool_force()->Add(value);
  // @@protoc_insertion_point(field_add:ArmState.left_tool_force)
}
inline const ::google::protobuf::RepeatedField<float>& ArmState::left_tool_force() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ArmState.left_tool_force)
  return _internal_left_tool_force();
}
inline ::google::protobuf::RepeatedField<float>* ArmState::mutable_left_tool_force()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ArmState.left_tool_force)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_left_tool_force();
}
inline const ::google::protobuf::RepeatedField<float>&
ArmState::_internal_left_tool_force() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_tool_force_;
}
inline ::google::protobuf::RepeatedField<float>* ArmState::_internal_mutable_left_tool_force() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.left_tool_force_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_arm_5fstate_2eproto_2epb_2eh
