// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint_state.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_joint_5fstate_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_joint_5fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_joint_5fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_joint_5fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_joint_5fstate_2eproto;
class JointState;
struct JointStateDefaultTypeInternal;
extern JointStateDefaultTypeInternal _JointState_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class JointState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:JointState) */ {
 public:
  inline JointState() : JointState(nullptr) {}
  ~JointState() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointState(
      ::google::protobuf::internal::ConstantInitialized);

  inline JointState(const JointState& from) : JointState(nullptr, from) {}
  inline JointState(JointState&& from) noexcept
      : JointState(nullptr, std::move(from)) {}
  inline JointState& operator=(const JointState& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointState& operator=(JointState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointState& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointState* internal_default_instance() {
    return reinterpret_cast<const JointState*>(
        &_JointState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JointState& a, JointState& b) { a.Swap(&b); }
  inline void Swap(JointState* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointState* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<JointState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JointState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JointState& from) { JointState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(JointState* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "JointState"; }

 protected:
  explicit JointState(::google::protobuf::Arena* arena);
  JointState(::google::protobuf::Arena* arena, const JointState& from);
  JointState(::google::protobuf::Arena* arena, JointState&& from) noexcept
      : JointState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStateFieldNumber = 1,
    kPositionFieldNumber = 2,
    kTorqueFieldNumber = 3,
    kFaultCodeFieldNumber = 4,
  };
  // uint32 state = 1;
  void clear_state() ;
  ::uint32_t state() const;
  void set_state(::uint32_t value);

  private:
  ::uint32_t _internal_state() const;
  void _internal_set_state(::uint32_t value);

  public:
  // float position = 2;
  void clear_position() ;
  float position() const;
  void set_position(float value);

  private:
  float _internal_position() const;
  void _internal_set_position(float value);

  public:
  // float torque = 3;
  void clear_torque() ;
  float torque() const;
  void set_torque(float value);

  private:
  float _internal_torque() const;
  void _internal_set_torque(float value);

  public:
  // uint32 fault_code = 4;
  void clear_fault_code() ;
  ::uint32_t fault_code() const;
  void set_fault_code(::uint32_t value);

  private:
  ::uint32_t _internal_fault_code() const;
  void _internal_set_fault_code(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:JointState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_JointState_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const JointState& from_msg);
    ::uint32_t state_;
    float position_;
    float torque_;
    ::uint32_t fault_code_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_5fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JointState

// uint32 state = 1;
inline void JointState::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0u;
}
inline ::uint32_t JointState::state() const {
  // @@protoc_insertion_point(field_get:JointState.state)
  return _internal_state();
}
inline void JointState::set_state(::uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:JointState.state)
}
inline ::uint32_t JointState::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_;
}
inline void JointState::_internal_set_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// float position = 2;
inline void JointState::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = 0;
}
inline float JointState::position() const {
  // @@protoc_insertion_point(field_get:JointState.position)
  return _internal_position();
}
inline void JointState::set_position(float value) {
  _internal_set_position(value);
  // @@protoc_insertion_point(field_set:JointState.position)
}
inline float JointState::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline void JointState::_internal_set_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = value;
}

// float torque = 3;
inline void JointState::clear_torque() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.torque_ = 0;
}
inline float JointState::torque() const {
  // @@protoc_insertion_point(field_get:JointState.torque)
  return _internal_torque();
}
inline void JointState::set_torque(float value) {
  _internal_set_torque(value);
  // @@protoc_insertion_point(field_set:JointState.torque)
}
inline float JointState::_internal_torque() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.torque_;
}
inline void JointState::_internal_set_torque(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.torque_ = value;
}

// uint32 fault_code = 4;
inline void JointState::clear_fault_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = 0u;
}
inline ::uint32_t JointState::fault_code() const {
  // @@protoc_insertion_point(field_get:JointState.fault_code)
  return _internal_fault_code();
}
inline void JointState::set_fault_code(::uint32_t value) {
  _internal_set_fault_code(value);
  // @@protoc_insertion_point(field_set:JointState.fault_code)
}
inline ::uint32_t JointState::_internal_fault_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fault_code_;
}
inline void JointState::_internal_set_fault_code(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_joint_5fstate_2eproto_2epb_2eh
