// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint_command.proto
// Protobuf C++ Version: 5.28.2

#include "joint_command.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr JointCommand::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : position_desired_{0},
        velocity_gain_{0},
        acceleration_gain_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JointCommand::JointCommand(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JointCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointCommandDefaultTypeInternal() {}
  union {
    JointCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointCommandDefaultTypeInternal _JointCommand_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_joint_5fcommand_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_joint_5fcommand_2eproto = nullptr;
const ::uint32_t
    TableStruct_joint_5fcommand_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::JointCommand, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::JointCommand, _impl_.position_desired_),
        PROTOBUF_FIELD_OFFSET(::JointCommand, _impl_.velocity_gain_),
        PROTOBUF_FIELD_OFFSET(::JointCommand, _impl_.acceleration_gain_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::JointCommand)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_JointCommand_default_instance_._instance,
};
const char descriptor_table_protodef_joint_5fcommand_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023joint_command.proto\"Z\n\014JointCommand\022\030\n"
    "\020position_desired\030\001 \001(\002\022\025\n\rvelocity_gain"
    "\030\002 \001(\002\022\031\n\021acceleration_gain\030\003 \001(\002b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_joint_5fcommand_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_joint_5fcommand_2eproto = {
    false,
    false,
    121,
    descriptor_table_protodef_joint_5fcommand_2eproto,
    "joint_command.proto",
    &descriptor_table_joint_5fcommand_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_joint_5fcommand_2eproto::offsets,
    file_level_enum_descriptors_joint_5fcommand_2eproto,
    file_level_service_descriptors_joint_5fcommand_2eproto,
};
// ===================================================================

class JointCommand::_Internal {
 public:
};

JointCommand::JointCommand(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:JointCommand)
}
JointCommand::JointCommand(
    ::google::protobuf::Arena* arena, const JointCommand& from)
    : JointCommand(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE JointCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void JointCommand::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_desired_),
           0,
           offsetof(Impl_, acceleration_gain_) -
               offsetof(Impl_, position_desired_) +
               sizeof(Impl_::acceleration_gain_));
}
JointCommand::~JointCommand() {
  // @@protoc_insertion_point(destructor:JointCommand)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JointCommand::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    JointCommand::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_JointCommand_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &JointCommand::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<JointCommand>(),
            ::google::protobuf::Message::GetNewImpl<JointCommand>(),
            ::google::protobuf::Message::GetClearImpl<JointCommand>(), &JointCommand::ByteSizeLong,
                &JointCommand::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(JointCommand, _impl_._cached_size_),
            false,
        },
        &JointCommand::kDescriptorMethods,
        &descriptor_table_joint_5fcommand_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* JointCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> JointCommand::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::JointCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float position_desired = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.position_desired_)}},
    // float velocity_gain = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.velocity_gain_)}},
    // float acceleration_gain = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.acceleration_gain_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float position_desired = 1;
    {PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.position_desired_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float velocity_gain = 2;
    {PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.velocity_gain_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float acceleration_gain = 3;
    {PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.acceleration_gain_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void JointCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:JointCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.position_desired_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.acceleration_gain_) -
      reinterpret_cast<char*>(&_impl_.position_desired_)) + sizeof(_impl_.acceleration_gain_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JointCommand::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JointCommand& this_ = static_cast<const JointCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JointCommand::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JointCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:JointCommand)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float position_desired = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_position_desired()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_position_desired(), target);
          }

          // float velocity_gain = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_velocity_gain()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_velocity_gain(), target);
          }

          // float acceleration_gain = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_acceleration_gain()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_acceleration_gain(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:JointCommand)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JointCommand::ByteSizeLong(const MessageLite& base) {
          const JointCommand& this_ = static_cast<const JointCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JointCommand::ByteSizeLong() const {
          const JointCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:JointCommand)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float position_desired = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_position_desired()) != 0) {
              total_size += 5;
            }
            // float velocity_gain = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_velocity_gain()) != 0) {
              total_size += 5;
            }
            // float acceleration_gain = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_acceleration_gain()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JointCommand::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JointCommand*>(&to_msg);
  auto& from = static_cast<const JointCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:JointCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_position_desired()) != 0) {
    _this->_impl_.position_desired_ = from._impl_.position_desired_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_velocity_gain()) != 0) {
    _this->_impl_.velocity_gain_ = from._impl_.velocity_gain_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_acceleration_gain()) != 0) {
    _this->_impl_.acceleration_gain_ = from._impl_.acceleration_gain_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JointCommand::CopyFrom(const JointCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JointCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JointCommand::InternalSwap(JointCommand* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.acceleration_gain_)
      + sizeof(JointCommand::_impl_.acceleration_gain_)
      - PROTOBUF_FIELD_OFFSET(JointCommand, _impl_.position_desired_)>(
          reinterpret_cast<char*>(&_impl_.position_desired_),
          reinterpret_cast<char*>(&other->_impl_.position_desired_));
}

::google::protobuf::Metadata JointCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_joint_5fcommand_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
