// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint_command.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_joint_5fcommand_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_joint_5fcommand_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_joint_5fcommand_2eproto;
class JointCommand;
struct JointCommandDefaultTypeInternal;
extern JointCommandDefaultTypeInternal _JointCommand_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class JointCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:JointCommand) */ {
 public:
  inline JointCommand() : JointCommand(nullptr) {}
  ~JointCommand() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline JointCommand(const JointCommand& from) : JointCommand(nullptr, from) {}
  inline JointCommand(JointCommand&& from) noexcept
      : JointCommand(nullptr, std::move(from)) {}
  inline JointCommand& operator=(const JointCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointCommand& operator=(JointCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointCommand* internal_default_instance() {
    return reinterpret_cast<const JointCommand*>(
        &_JointCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JointCommand& a, JointCommand& b) { a.Swap(&b); }
  inline void Swap(JointCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointCommand* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<JointCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JointCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JointCommand& from) { JointCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(JointCommand* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "JointCommand"; }

 protected:
  explicit JointCommand(::google::protobuf::Arena* arena);
  JointCommand(::google::protobuf::Arena* arena, const JointCommand& from);
  JointCommand(::google::protobuf::Arena* arena, JointCommand&& from) noexcept
      : JointCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionDesiredFieldNumber = 1,
    kVelocityGainFieldNumber = 2,
    kAccelerationGainFieldNumber = 3,
  };
  // float position_desired = 1;
  void clear_position_desired() ;
  float position_desired() const;
  void set_position_desired(float value);

  private:
  float _internal_position_desired() const;
  void _internal_set_position_desired(float value);

  public:
  // float velocity_gain = 2;
  void clear_velocity_gain() ;
  float velocity_gain() const;
  void set_velocity_gain(float value);

  private:
  float _internal_velocity_gain() const;
  void _internal_set_velocity_gain(float value);

  public:
  // float acceleration_gain = 3;
  void clear_acceleration_gain() ;
  float acceleration_gain() const;
  void set_acceleration_gain(float value);

  private:
  float _internal_acceleration_gain() const;
  void _internal_set_acceleration_gain(float value);

  public:
  // @@protoc_insertion_point(class_scope:JointCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_JointCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const JointCommand& from_msg);
    float position_desired_;
    float velocity_gain_;
    float acceleration_gain_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_5fcommand_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JointCommand

// float position_desired = 1;
inline void JointCommand::clear_position_desired() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_desired_ = 0;
}
inline float JointCommand::position_desired() const {
  // @@protoc_insertion_point(field_get:JointCommand.position_desired)
  return _internal_position_desired();
}
inline void JointCommand::set_position_desired(float value) {
  _internal_set_position_desired(value);
  // @@protoc_insertion_point(field_set:JointCommand.position_desired)
}
inline float JointCommand::_internal_position_desired() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_desired_;
}
inline void JointCommand::_internal_set_position_desired(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_desired_ = value;
}

// float velocity_gain = 2;
inline void JointCommand::clear_velocity_gain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_gain_ = 0;
}
inline float JointCommand::velocity_gain() const {
  // @@protoc_insertion_point(field_get:JointCommand.velocity_gain)
  return _internal_velocity_gain();
}
inline void JointCommand::set_velocity_gain(float value) {
  _internal_set_velocity_gain(value);
  // @@protoc_insertion_point(field_set:JointCommand.velocity_gain)
}
inline float JointCommand::_internal_velocity_gain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_gain_;
}
inline void JointCommand::_internal_set_velocity_gain(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_gain_ = value;
}

// float acceleration_gain = 3;
inline void JointCommand::clear_acceleration_gain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acceleration_gain_ = 0;
}
inline float JointCommand::acceleration_gain() const {
  // @@protoc_insertion_point(field_get:JointCommand.acceleration_gain)
  return _internal_acceleration_gain();
}
inline void JointCommand::set_acceleration_gain(float value) {
  _internal_set_acceleration_gain(value);
  // @@protoc_insertion_point(field_set:JointCommand.acceleration_gain)
}
inline float JointCommand::_internal_acceleration_gain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.acceleration_gain_;
}
inline void JointCommand::_internal_set_acceleration_gain(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acceleration_gain_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto_2epb_2eh
