// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: motion_platform_state.proto
// Protobuf C++ Version: 5.28.2

#include "motion_platform_state.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MotionPlatformState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : state_{0u},
        fault_code_{0u},
        linear_x_{0},
        linear_y_{0},
        angular_z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MotionPlatformState::MotionPlatformState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MotionPlatformStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MotionPlatformStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MotionPlatformStateDefaultTypeInternal() {}
  union {
    MotionPlatformState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MotionPlatformStateDefaultTypeInternal _MotionPlatformState_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_motion_5fplatform_5fstate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_motion_5fplatform_5fstate_2eproto = nullptr;
const ::uint32_t
    TableStruct_motion_5fplatform_5fstate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _impl_.fault_code_),
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _impl_.linear_x_),
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _impl_.linear_y_),
        PROTOBUF_FIELD_OFFSET(::MotionPlatformState, _impl_.angular_z_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MotionPlatformState)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_MotionPlatformState_default_instance_._instance,
};
const char descriptor_table_protodef_motion_5fplatform_5fstate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033motion_platform_state.proto\"o\n\023MotionP"
    "latformState\022\r\n\005state\030\001 \001(\r\022\022\n\nfault_cod"
    "e\030\002 \001(\r\022\020\n\010linear_x\030\003 \001(\002\022\020\n\010linear_y\030\004 "
    "\001(\002\022\021\n\tangular_z\030\005 \001(\002b\006proto3"
};
static ::absl::once_flag descriptor_table_motion_5fplatform_5fstate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_motion_5fplatform_5fstate_2eproto = {
    false,
    false,
    150,
    descriptor_table_protodef_motion_5fplatform_5fstate_2eproto,
    "motion_platform_state.proto",
    &descriptor_table_motion_5fplatform_5fstate_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_motion_5fplatform_5fstate_2eproto::offsets,
    file_level_enum_descriptors_motion_5fplatform_5fstate_2eproto,
    file_level_service_descriptors_motion_5fplatform_5fstate_2eproto,
};
// ===================================================================

class MotionPlatformState::_Internal {
 public:
};

MotionPlatformState::MotionPlatformState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MotionPlatformState)
}
MotionPlatformState::MotionPlatformState(
    ::google::protobuf::Arena* arena, const MotionPlatformState& from)
    : MotionPlatformState(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MotionPlatformState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MotionPlatformState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, state_),
           0,
           offsetof(Impl_, angular_z_) -
               offsetof(Impl_, state_) +
               sizeof(Impl_::angular_z_));
}
MotionPlatformState::~MotionPlatformState() {
  // @@protoc_insertion_point(destructor:MotionPlatformState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MotionPlatformState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MotionPlatformState::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MotionPlatformState_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MotionPlatformState::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MotionPlatformState>(),
            ::google::protobuf::Message::GetNewImpl<MotionPlatformState>(),
            ::google::protobuf::Message::GetClearImpl<MotionPlatformState>(), &MotionPlatformState::ByteSizeLong,
                &MotionPlatformState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_._cached_size_),
            false,
        },
        &MotionPlatformState::kDescriptorMethods,
        &descriptor_table_motion_5fplatform_5fstate_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MotionPlatformState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> MotionPlatformState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MotionPlatformState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MotionPlatformState, _impl_.state_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.state_)}},
    // uint32 fault_code = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MotionPlatformState, _impl_.fault_code_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.fault_code_)}},
    // float linear_x = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.linear_x_)}},
    // float linear_y = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.linear_y_)}},
    // float angular_z = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.angular_z_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 state = 1;
    {PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 fault_code = 2;
    {PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.fault_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // float linear_x = 3;
    {PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.linear_x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float linear_y = 4;
    {PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.linear_y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float angular_z = 5;
    {PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.angular_z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MotionPlatformState::Clear() {
// @@protoc_insertion_point(message_clear_start:MotionPlatformState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.state_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.angular_z_) -
      reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.angular_z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MotionPlatformState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MotionPlatformState& this_ = static_cast<const MotionPlatformState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MotionPlatformState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MotionPlatformState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MotionPlatformState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 state = 1;
          if (this_._internal_state() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_state(), target);
          }

          // uint32 fault_code = 2;
          if (this_._internal_fault_code() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_fault_code(), target);
          }

          // float linear_x = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_linear_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_linear_x(), target);
          }

          // float linear_y = 4;
          if (::absl::bit_cast<::uint32_t>(this_._internal_linear_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                4, this_._internal_linear_y(), target);
          }

          // float angular_z = 5;
          if (::absl::bit_cast<::uint32_t>(this_._internal_angular_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                5, this_._internal_angular_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MotionPlatformState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MotionPlatformState::ByteSizeLong(const MessageLite& base) {
          const MotionPlatformState& this_ = static_cast<const MotionPlatformState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MotionPlatformState::ByteSizeLong() const {
          const MotionPlatformState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MotionPlatformState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 state = 1;
            if (this_._internal_state() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_state());
            }
            // uint32 fault_code = 2;
            if (this_._internal_fault_code() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_fault_code());
            }
            // float linear_x = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_linear_x()) != 0) {
              total_size += 5;
            }
            // float linear_y = 4;
            if (::absl::bit_cast<::uint32_t>(this_._internal_linear_y()) != 0) {
              total_size += 5;
            }
            // float angular_z = 5;
            if (::absl::bit_cast<::uint32_t>(this_._internal_angular_z()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MotionPlatformState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MotionPlatformState*>(&to_msg);
  auto& from = static_cast<const MotionPlatformState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MotionPlatformState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_state() != 0) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  if (from._internal_fault_code() != 0) {
    _this->_impl_.fault_code_ = from._impl_.fault_code_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_linear_x()) != 0) {
    _this->_impl_.linear_x_ = from._impl_.linear_x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_linear_y()) != 0) {
    _this->_impl_.linear_y_ = from._impl_.linear_y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_angular_z()) != 0) {
    _this->_impl_.angular_z_ = from._impl_.angular_z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MotionPlatformState::CopyFrom(const MotionPlatformState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MotionPlatformState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MotionPlatformState::InternalSwap(MotionPlatformState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.angular_z_)
      + sizeof(MotionPlatformState::_impl_.angular_z_)
      - PROTOBUF_FIELD_OFFSET(MotionPlatformState, _impl_.state_)>(
          reinterpret_cast<char*>(&_impl_.state_),
          reinterpret_cast<char*>(&other->_impl_.state_));
}

::google::protobuf::Metadata MotionPlatformState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_motion_5fplatform_5fstate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
