// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: motion_platform_state.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fstate_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_motion_5fplatform_5fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_motion_5fplatform_5fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_motion_5fplatform_5fstate_2eproto;
class MotionPlatformState;
struct MotionPlatformStateDefaultTypeInternal;
extern MotionPlatformStateDefaultTypeInternal _MotionPlatformState_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class MotionPlatformState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MotionPlatformState) */ {
 public:
  inline MotionPlatformState() : MotionPlatformState(nullptr) {}
  ~MotionPlatformState() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MotionPlatformState(
      ::google::protobuf::internal::ConstantInitialized);

  inline MotionPlatformState(const MotionPlatformState& from) : MotionPlatformState(nullptr, from) {}
  inline MotionPlatformState(MotionPlatformState&& from) noexcept
      : MotionPlatformState(nullptr, std::move(from)) {}
  inline MotionPlatformState& operator=(const MotionPlatformState& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotionPlatformState& operator=(MotionPlatformState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotionPlatformState& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotionPlatformState* internal_default_instance() {
    return reinterpret_cast<const MotionPlatformState*>(
        &_MotionPlatformState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MotionPlatformState& a, MotionPlatformState& b) { a.Swap(&b); }
  inline void Swap(MotionPlatformState* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotionPlatformState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotionPlatformState* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MotionPlatformState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MotionPlatformState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MotionPlatformState& from) { MotionPlatformState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MotionPlatformState* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MotionPlatformState"; }

 protected:
  explicit MotionPlatformState(::google::protobuf::Arena* arena);
  MotionPlatformState(::google::protobuf::Arena* arena, const MotionPlatformState& from);
  MotionPlatformState(::google::protobuf::Arena* arena, MotionPlatformState&& from) noexcept
      : MotionPlatformState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStateFieldNumber = 1,
    kFaultCodeFieldNumber = 2,
    kLinearXFieldNumber = 3,
    kLinearYFieldNumber = 4,
    kAngularZFieldNumber = 5,
  };
  // uint32 state = 1;
  void clear_state() ;
  ::uint32_t state() const;
  void set_state(::uint32_t value);

  private:
  ::uint32_t _internal_state() const;
  void _internal_set_state(::uint32_t value);

  public:
  // uint32 fault_code = 2;
  void clear_fault_code() ;
  ::uint32_t fault_code() const;
  void set_fault_code(::uint32_t value);

  private:
  ::uint32_t _internal_fault_code() const;
  void _internal_set_fault_code(::uint32_t value);

  public:
  // float linear_x = 3;
  void clear_linear_x() ;
  float linear_x() const;
  void set_linear_x(float value);

  private:
  float _internal_linear_x() const;
  void _internal_set_linear_x(float value);

  public:
  // float linear_y = 4;
  void clear_linear_y() ;
  float linear_y() const;
  void set_linear_y(float value);

  private:
  float _internal_linear_y() const;
  void _internal_set_linear_y(float value);

  public:
  // float angular_z = 5;
  void clear_angular_z() ;
  float angular_z() const;
  void set_angular_z(float value);

  private:
  float _internal_angular_z() const;
  void _internal_set_angular_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:MotionPlatformState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MotionPlatformState_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MotionPlatformState& from_msg);
    ::uint32_t state_;
    ::uint32_t fault_code_;
    float linear_x_;
    float linear_y_;
    float angular_z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_motion_5fplatform_5fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MotionPlatformState

// uint32 state = 1;
inline void MotionPlatformState::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0u;
}
inline ::uint32_t MotionPlatformState::state() const {
  // @@protoc_insertion_point(field_get:MotionPlatformState.state)
  return _internal_state();
}
inline void MotionPlatformState::set_state(::uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:MotionPlatformState.state)
}
inline ::uint32_t MotionPlatformState::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_;
}
inline void MotionPlatformState::_internal_set_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// uint32 fault_code = 2;
inline void MotionPlatformState::clear_fault_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = 0u;
}
inline ::uint32_t MotionPlatformState::fault_code() const {
  // @@protoc_insertion_point(field_get:MotionPlatformState.fault_code)
  return _internal_fault_code();
}
inline void MotionPlatformState::set_fault_code(::uint32_t value) {
  _internal_set_fault_code(value);
  // @@protoc_insertion_point(field_set:MotionPlatformState.fault_code)
}
inline ::uint32_t MotionPlatformState::_internal_fault_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fault_code_;
}
inline void MotionPlatformState::_internal_set_fault_code(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_code_ = value;
}

// float linear_x = 3;
inline void MotionPlatformState::clear_linear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_x_ = 0;
}
inline float MotionPlatformState::linear_x() const {
  // @@protoc_insertion_point(field_get:MotionPlatformState.linear_x)
  return _internal_linear_x();
}
inline void MotionPlatformState::set_linear_x(float value) {
  _internal_set_linear_x(value);
  // @@protoc_insertion_point(field_set:MotionPlatformState.linear_x)
}
inline float MotionPlatformState::_internal_linear_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linear_x_;
}
inline void MotionPlatformState::_internal_set_linear_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_x_ = value;
}

// float linear_y = 4;
inline void MotionPlatformState::clear_linear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_y_ = 0;
}
inline float MotionPlatformState::linear_y() const {
  // @@protoc_insertion_point(field_get:MotionPlatformState.linear_y)
  return _internal_linear_y();
}
inline void MotionPlatformState::set_linear_y(float value) {
  _internal_set_linear_y(value);
  // @@protoc_insertion_point(field_set:MotionPlatformState.linear_y)
}
inline float MotionPlatformState::_internal_linear_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linear_y_;
}
inline void MotionPlatformState::_internal_set_linear_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_y_ = value;
}

// float angular_z = 5;
inline void MotionPlatformState::clear_angular_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angular_z_ = 0;
}
inline float MotionPlatformState::angular_z() const {
  // @@protoc_insertion_point(field_get:MotionPlatformState.angular_z)
  return _internal_angular_z();
}
inline void MotionPlatformState::set_angular_z(float value) {
  _internal_set_angular_z(value);
  // @@protoc_insertion_point(field_set:MotionPlatformState.angular_z)
}
inline float MotionPlatformState::_internal_angular_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angular_z_;
}
inline void MotionPlatformState::_internal_set_angular_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angular_z_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fstate_2eproto_2epb_2eh
