// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: motion_platform_command.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fcommand_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fcommand_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_motion_5fplatform_5fcommand_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_motion_5fplatform_5fcommand_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_motion_5fplatform_5fcommand_2eproto;
class MotionPlatformCommand;
struct MotionPlatformCommandDefaultTypeInternal;
extern MotionPlatformCommandDefaultTypeInternal _MotionPlatformCommand_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class MotionPlatformCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MotionPlatformCommand) */ {
 public:
  inline MotionPlatformCommand() : MotionPlatformCommand(nullptr) {}
  ~MotionPlatformCommand() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MotionPlatformCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline MotionPlatformCommand(const MotionPlatformCommand& from) : MotionPlatformCommand(nullptr, from) {}
  inline MotionPlatformCommand(MotionPlatformCommand&& from) noexcept
      : MotionPlatformCommand(nullptr, std::move(from)) {}
  inline MotionPlatformCommand& operator=(const MotionPlatformCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotionPlatformCommand& operator=(MotionPlatformCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotionPlatformCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotionPlatformCommand* internal_default_instance() {
    return reinterpret_cast<const MotionPlatformCommand*>(
        &_MotionPlatformCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MotionPlatformCommand& a, MotionPlatformCommand& b) { a.Swap(&b); }
  inline void Swap(MotionPlatformCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotionPlatformCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotionPlatformCommand* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MotionPlatformCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MotionPlatformCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MotionPlatformCommand& from) { MotionPlatformCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MotionPlatformCommand* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MotionPlatformCommand"; }

 protected:
  explicit MotionPlatformCommand(::google::protobuf::Arena* arena);
  MotionPlatformCommand(::google::protobuf::Arena* arena, const MotionPlatformCommand& from);
  MotionPlatformCommand(::google::protobuf::Arena* arena, MotionPlatformCommand&& from) noexcept
      : MotionPlatformCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRequestStateFieldNumber = 1,
    kLinearYFieldNumber = 2,
    kLinearXFieldNumber = 3,
    kAngularZFieldNumber = 4,
    kMaxLinearVelocityCoeffFieldNumber = 5,
    kMaxAngularVelocityCoeffFieldNumber = 6,
  };
  // uint32 request_state = 1;
  void clear_request_state() ;
  ::uint32_t request_state() const;
  void set_request_state(::uint32_t value);

  private:
  ::uint32_t _internal_request_state() const;
  void _internal_set_request_state(::uint32_t value);

  public:
  // float linear_y = 2;
  void clear_linear_y() ;
  float linear_y() const;
  void set_linear_y(float value);

  private:
  float _internal_linear_y() const;
  void _internal_set_linear_y(float value);

  public:
  // float linear_x = 3;
  void clear_linear_x() ;
  float linear_x() const;
  void set_linear_x(float value);

  private:
  float _internal_linear_x() const;
  void _internal_set_linear_x(float value);

  public:
  // float angular_z = 4;
  void clear_angular_z() ;
  float angular_z() const;
  void set_angular_z(float value);

  private:
  float _internal_angular_z() const;
  void _internal_set_angular_z(float value);

  public:
  // float max_linear_velocity_coeff = 5;
  void clear_max_linear_velocity_coeff() ;
  float max_linear_velocity_coeff() const;
  void set_max_linear_velocity_coeff(float value);

  private:
  float _internal_max_linear_velocity_coeff() const;
  void _internal_set_max_linear_velocity_coeff(float value);

  public:
  // float max_angular_velocity_coeff = 6;
  void clear_max_angular_velocity_coeff() ;
  float max_angular_velocity_coeff() const;
  void set_max_angular_velocity_coeff(float value);

  private:
  float _internal_max_angular_velocity_coeff() const;
  void _internal_set_max_angular_velocity_coeff(float value);

  public:
  // @@protoc_insertion_point(class_scope:MotionPlatformCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MotionPlatformCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MotionPlatformCommand& from_msg);
    ::uint32_t request_state_;
    float linear_y_;
    float linear_x_;
    float angular_z_;
    float max_linear_velocity_coeff_;
    float max_angular_velocity_coeff_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_motion_5fplatform_5fcommand_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MotionPlatformCommand

// uint32 request_state = 1;
inline void MotionPlatformCommand::clear_request_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_state_ = 0u;
}
inline ::uint32_t MotionPlatformCommand::request_state() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.request_state)
  return _internal_request_state();
}
inline void MotionPlatformCommand::set_request_state(::uint32_t value) {
  _internal_set_request_state(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.request_state)
}
inline ::uint32_t MotionPlatformCommand::_internal_request_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_state_;
}
inline void MotionPlatformCommand::_internal_set_request_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_state_ = value;
}

// float linear_y = 2;
inline void MotionPlatformCommand::clear_linear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_y_ = 0;
}
inline float MotionPlatformCommand::linear_y() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.linear_y)
  return _internal_linear_y();
}
inline void MotionPlatformCommand::set_linear_y(float value) {
  _internal_set_linear_y(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.linear_y)
}
inline float MotionPlatformCommand::_internal_linear_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linear_y_;
}
inline void MotionPlatformCommand::_internal_set_linear_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_y_ = value;
}

// float linear_x = 3;
inline void MotionPlatformCommand::clear_linear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_x_ = 0;
}
inline float MotionPlatformCommand::linear_x() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.linear_x)
  return _internal_linear_x();
}
inline void MotionPlatformCommand::set_linear_x(float value) {
  _internal_set_linear_x(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.linear_x)
}
inline float MotionPlatformCommand::_internal_linear_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linear_x_;
}
inline void MotionPlatformCommand::_internal_set_linear_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_x_ = value;
}

// float angular_z = 4;
inline void MotionPlatformCommand::clear_angular_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angular_z_ = 0;
}
inline float MotionPlatformCommand::angular_z() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.angular_z)
  return _internal_angular_z();
}
inline void MotionPlatformCommand::set_angular_z(float value) {
  _internal_set_angular_z(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.angular_z)
}
inline float MotionPlatformCommand::_internal_angular_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angular_z_;
}
inline void MotionPlatformCommand::_internal_set_angular_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angular_z_ = value;
}

// float max_linear_velocity_coeff = 5;
inline void MotionPlatformCommand::clear_max_linear_velocity_coeff() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_linear_velocity_coeff_ = 0;
}
inline float MotionPlatformCommand::max_linear_velocity_coeff() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.max_linear_velocity_coeff)
  return _internal_max_linear_velocity_coeff();
}
inline void MotionPlatformCommand::set_max_linear_velocity_coeff(float value) {
  _internal_set_max_linear_velocity_coeff(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.max_linear_velocity_coeff)
}
inline float MotionPlatformCommand::_internal_max_linear_velocity_coeff() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_linear_velocity_coeff_;
}
inline void MotionPlatformCommand::_internal_set_max_linear_velocity_coeff(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_linear_velocity_coeff_ = value;
}

// float max_angular_velocity_coeff = 6;
inline void MotionPlatformCommand::clear_max_angular_velocity_coeff() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_angular_velocity_coeff_ = 0;
}
inline float MotionPlatformCommand::max_angular_velocity_coeff() const {
  // @@protoc_insertion_point(field_get:MotionPlatformCommand.max_angular_velocity_coeff)
  return _internal_max_angular_velocity_coeff();
}
inline void MotionPlatformCommand::set_max_angular_velocity_coeff(float value) {
  _internal_set_max_angular_velocity_coeff(value);
  // @@protoc_insertion_point(field_set:MotionPlatformCommand.max_angular_velocity_coeff)
}
inline float MotionPlatformCommand::_internal_max_angular_velocity_coeff() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_angular_velocity_coeff_;
}
inline void MotionPlatformCommand::_internal_set_max_angular_velocity_coeff(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_angular_velocity_coeff_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_motion_5fplatform_5fcommand_2eproto_2epb_2eh
